---
  name: 'Goncalo Abecasis'
  gid: 't53jWtYAAAAJ'
---
  name: 'Trivellore Raghunathan'
  gid: 'zuw_C0cAAAAJ'
---
  name: 'Roderick Little'
  gid: 'gj7OdjcAAAAJ'
---
  name: 'Thomas M. Braun'
  gid: 'Sg9SqwkAAAAJ'
---
  name: 'Hui Jiang'
  gid: 'LszKw2cAAAAJ'
---
  name: 'Michael Boehnke'
  gid: 'nGgivIAAAAAJ'
---
  name: 'James M. Lepkowski'
  gid: 'L42PDQ8AAAAJ'
---
  name: 'Sebastian Zöllner'
  gid: 'b4SbbzYAAAAJ'
