---
  name: 'Goncalo Abecasis'
  gid: 't53jWtYAAAAJ'
---
  name: 'Trivellore Raghunathan'
  gid: 'zuw_C0cAAAAJ'
---
  name: 'Roderick Little'
  gid: 'gj7OdjcAAAAJ'
---
  name: 'Thomas M. Braun'
  gid: 'Sg9SqwkAAAAJ'
---
  name: 'Hui Jiang'
  gid: 'LszKw2cAAAAJ'
---
  name: 'Michael Boehnke'
  gid: 'nGgivIAAAAAJ'
---
  name: 'James M. Lepkowski'
  gid: 'L42PDQ8AAAAJ'
---
  name: 'Sebastian Zöllner'
  gid: 'b4SbbzYAAAAJ'
---
  name: 'Brisa N Sanchez'
  gid: 'o-onTfUAAAAJ'
---
  name: 'yi li'
  gid: '-3V3mFkAAAAJ'
---
  name: 'Laura J Scott'
  gid: '0GvpFGgAAAAJ'
---
  name: 'Michael Elliot'
  gid: '6T-J2gsAAAAJ'
---
  name: 'Robert A. Parker'
  gid: 'dLHQTugAAAAJ'
---
  name: 'Alex Tsodikov'
  gid: 'SCZh9zMAAAAJ'
---
  name: 'Xiaoquan Wen'
  gid: 'kaO2JQwAAAAJ'
---
  name: 'Susan Murray'
  gid: 'tIJD49EAAAAJ'
---
  name: 'Hyun Min Kang'
  gid: '8e0jy0IAAAAJ'
---
  name: 'Timothy D. Johnson'
  gid: 'YYJXugMAAAAJ'
---
  name: 'Peter Xuekun Song'
  gid: 'bR8pPwsAAAAJ'
---
  name: 'Kelley M. Kidwell'
  gid: 'h25AXWwAAAAJ'
---
  name: 'Min Zhang'
  gid: '9TKFKYcAAAAJ'
---
  name: 'Cathie Spino'
  gid: 'sGT9GsQAAAAJ'
---
  name: 'Lili Zhao'
  gid: '72kNFngAAAAJ'
---
  name: 'Sehee Kim'
  gid: 'osbjOoQAAAAJ'
